<?php

namespace app\modules\user\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;

/**
 * Social auth controller for User module
 */
class ClientController extends Controller
{

    public $layout = '@user/views/layouts/dashboard';
    public $icon, $dataModel, $pageName, $breadcrumbs;
    public $jsMessages = [];
    public $dashboard = false;
    public $enableStatistic = true;
    public $buttons = [];
    public $asset;

    public function beforeAction($action)
    {
        $this->asset = \app\modules\user\DashboardAsset::register($this->getView());
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        //  'actions' => ['logout'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }
    public function redirectPage($isNewRecord, $post, $action = ['index'])
    {

        Yii::$app->session->setFlash('success', Yii::t('app/default', ($isNewRecord) ? 'SUCCESS_CREATE' : 'SUCCESS_UPDATE'));
        $redirect = (isset($post['redirect'])) ? $post['redirect'] : Yii::$app->request->url;

        if ($isNewRecord) {
            return $this->redirect($action);
        }
        if (!Yii::$app->request->isAjax)
            return Yii::$app->response->redirect($redirect);
    }
    public function actionCreate()
    {
        return $this->actionUpdate(false);
    }
}
